version = 0.1

[default.deploy.parameters]
stack_name = "hmunoz-devsite-backend"
resolve_s3 = true
s3_prefix = "hmunoz-devsite-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "mx-central-1"
